"""add categories

Revision ID: f9444e1ba5df
Revises: acc8ae75f9e8
Create Date: 2026-01-06 00:10:08.091803

"""
from typing import Sequence, Union

import advanced_alchemy
import sqlalchemy as sa
from alembic import op


# revision identifiers, used by Alembic.
revision: str = 'f9444e1ba5df'
down_revision: Union[str, Sequence[str], None] = 'acc8ae75f9e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('created_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.Column('updated_at', advanced_alchemy.types.datetime.DateTimeUTC(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_categories')),
    sa.UniqueConstraint('name', name=op.f('uq_categories_name'))
    )
    op.create_table('book_categories',
    sa.Column('book_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('category_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.ForeignKeyConstraint(['book_id'], ['books.id'], name=op.f('fk_book_categories_book_id_books'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['category_id'], ['categories.id'], name=op.f('fk_book_categories_category_id_categories'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('book_id', 'category_id', name=op.f('pk_book_categories'))
    )
    op.create_index(op.f('ix_book_categories_book_id'), 'book_categories', ['book_id'], unique=False)
    op.create_index(op.f('ix_book_categories_category_id'), 'book_categories', ['category_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_book_categories_category_id'), table_name='book_categories')
    op.drop_index(op.f('ix_book_categories_book_id'), table_name='book_categories')
    op.drop_table('book_categories')
    op.drop_table('categories')
    # ### end Alembic commands ###
